# Adaptive Media shortcuts
Ctrl+i script-binding adaptive/show-info
i script-binding stats/display-stats
I script-binding stats/display-stats-toggle
a cycle audio
s cycle sub
S cycle sub down
v cycle sub-visibility
d cycle deband
Ctrl+h cycle-values hwdec "auto-safe" "no"
SPACE cycle pause
RIGHT seek 5
LEFT seek -5
UP seek 60
DOWN seek -60
[ add speed -0.1
] add speed 0.1
BACKSPACE set speed 1.0
Ctrl+s screenshot video
f cycle fullscreen
ESC set fullscreen no
